# kategori

GET http://localhost:3000/kategori

###
GET http://localhost:3000/kategori/637222de356396bb553b67ef


###
POST http://localhost:3000/kategori
Content-Type: application/json

{
    "id" : 3,
    "nama_kategori" : "Fantasi"
}

###
PATCH http://localhost:3000/kategori/637222de356396bb553b67ef
Content-Type: application/json

{
    "id" : 2,
    "nama_kategori" : "jamal"
}

###
DELETE  http://localhost:3000/kategori/6378996e50523fe95a244071



# Film Artis

# get film Artis
###
GET http://localhost:3000/filmArtis

###
POST http://localhost:3000/filmArtis
Content-Type: application/json

{
    "id_film_artis" : 2,
    "id_film" : 1,
    "id_artis" : 1
}

# get By ID Film Artis
###
GET http://localhost:3000/filmArtis/63723238356396bb553b6807

###
DELETE  http://localhost:3000/filmArtis/63723deacfcff8b3b22d4df3


# Artis
###

GET http://localhost:3000/Artis

###

POST http://localhost:3000/Artis
Content-Type: application/json

{
    "id_artis" : 1,
    "nama_lengkap" : "dilf",
    "gambar" : "hgahwuhduwhdwkjankw"
}

###

GET http://localhost:3000/Artis/6374cc9dba27e748fa950651

###

DELETE  http://localhost:3000/Artis/63720382356396bb553b67d6


# Film
###

GET http://localhost:3000/Film

###

POST http://localhost:3000/Film
Content-Type: application/json

{
    "id_film" : 6,
    "id_kategori" : "6381c563d0893a41a7f6751f",
    "title" : "mabok cinta",
    "durasi" : "123 min",
    "umur" : 10,
    "rating" : "8.0",
    "tahun_terbit" : 2004,
    "overview" : "mantap mantap mantap",
    "descripsi" : "mantap mantap mantap",
    "garis_cerita" : "mantap mantap mantap",
    "gambar" : "https://m.media-amazon.com/images/M/MV5BMTU2NjA1ODgzMF5BMl5BanBnXkFtZTgwMTM2MTI4MjE@._V1_SX300.jpg"
}

###

GET http://localhost:3000/Film/6378998e50523fe95a244078

###

DELETE  http://localhost:3000/Film/6381ce78d0893a41a7f67533