# kategori

GET http://localhost:3000/kategori

###
GET http://localhost:3000/kategori/6381c563d0893a41a7f6751f


###
POST http://localhost:3000/kategori
Content-Type: application/json

{
    "id" : 3,
    "nama_kategori" : "Fantasi"
}

###
PATCH http://localhost:3000/kategori/637222de356396bb553b67ef
Content-Type: application/json

{
    "id" : 2,
    "nama_kategori" : "jamal"
}

###
DELETE  http://localhost:3000/kategori/6378996e50523fe95a244071



# Film Artis

# get film Artis
###
GET http://localhost:3000/filmArtis

###
POST http://localhost:3000/filmArtis
Content-Type: application/json

{
    "id_film_artis" : 1,
    "id_film" : "6381c59dd0893a41a7f67526",
    "id_artis" : "6378998a50523fe95a244076"
}

# get By ID Film Artis
###
GET http://localhost:3000/filmArtis/6378998650523fe95a244074

###
DELETE  http://localhost:3000/filmArtis/6389a19fb70cbb730e92ce28


# Artis
###

GET http://localhost:3000/Artis

###

POST http://localhost:3000/Artis
Content-Type: application/json

{
    "id_artis" : 1,
    "nama_lengkap" : "dilf",
    "gambar" : "hgahwuhduwhdwkjankw"
}

###

GET http://localhost:3000/Artis/6378998a50523fe95a244076

###

DELETE  http://localhost:3000/Artis/63720382356396bb553b67d6


# Film
###

GET http://localhost:3000/Film

###

POST http://localhost:3000/Film
Content-Type: application/json

{
    "id_film" : 6,
    "id_kategori" : "6381c56dd0893a41a7f67521",
    "title" : "bapak kau",
    "durasi" : "123 min",
    "umur" : 10,
    "rating" : "8.0",
    "gendre" : "Action",
    "tahun_terbit" : 2004,
    "overview" : "mantap mantap mantap",
    "descripsi" : "mantap mantap mantap",
    "garis_cerita" : "mantap mantap mantap",
    "gambar" : "https://m.media-amazon.com/images/M/MV5BMjIwMjE1Nzc4NV5BMl5BanBnXkFtZTgwNDg4OTA1NzM@._V1_SX300.jpg"
}

###

GET http://localhost:3000/Film/6381c59dd0893a41a7f67526

###

DELETE  http://localhost:3000/Film/6389998dd263774d2e497f7f